spring:
  application:
    name: config-server

profiles:
    active: docker

server:
  port: ${PORT:8888}

eureka:
  instance:
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
        management.context-path: /actuator
    client:
      register-with-eureka: true
      fetch-registery: true
      service-url:
        defaultZone: ${EUREKA_SERVICE_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"
