profiles:
    active: docker

eureka:
  instance:
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://registryService:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
